### ISSUE TITLE
Actividad-1-infografia-IsaacCS1

### ISSUE THREAD

**Issue by IsaacCS1** [SistemasTecTlaxiaco/actividad-1-infografia-IsaacCS1#2]
[MODELO EN CASCADA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-IsaacCS1/files/12565657/MODELO.EN.CASCADA.pdf)

**Comment by ka194** [comment]
parte de la infografía: 4
coherencia: 4
Organización: 4
diseño: 4
creatividad: 4

calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
